In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10], [15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[0][1]

10

In [8]:
np_matrix_2d = np.array([[5,10], [20,30]])
np_matrix_2d                              

array([[ 5, 10],
       [20, 30]])

In [9]:
np_matrix_2d.sum()

np.int64(65)

In [10]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [11]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
# Matrix Arithmetic

In [16]:
first_array = np.array([[10,20], [30,40]])

In [14]:
second_array = np.array([[5,15], [25,35]])

In [17]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [19]:
thirt_array = np.array([50,60])

In [20]:
firt_array + thirt_array

array([[ 60,  80],
       [ 80, 100]])

In [21]:
fourth_array = np.array([10,20,30,40,50])

In [22]:
first_array + fourth_array

ValueError: operands could not be broadcast together with shapes (2,2) (5,) 

In [23]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [25]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [26]:
# Matrix multiplication

In [27]:
first_array

array([[10, 20],
       [30, 40]])

In [28]:
second_array

array([[ 5, 15],
       [25, 35]])

In [30]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [31]:
# Dot product

In [32]:
first_matrix = np.array([10,20,30])

In [33]:
second_matrix = np.array([[2,3], [2,3], [2,3]])

In [34]:
first_matrix.dot(second_matrix)

array([120, 180])