In [1]:
import numpy as np

In [28]:
new_array = np.random.randint(1,10,5)

In [29]:
new_array

array([4, 9, 3, 6, 2])

In [31]:
new_array > 5

array([False,  True, False,  True, False])

In [5]:
new_array[new_array > 25]

array([61, 55, 80, 42, 31, 42, 72, 93, 74, 98, 55, 93, 63, 29, 69, 79, 87])

In [6]:
new_array[new_array < 25]

array([15, 16, 15])

In [8]:
matrix_array = np.array([[10,20], [20,30], [30,40]])

In [11]:
matrix_array.shape

(3, 2)

In [12]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [14]:
random_array = np.random.random((6,1))

In [15]:
random_array

array([[0.36894683],
       [0.87635348],
       [0.38514518],
       [0.21442169],
       [0.56360497],
       [0.63600393]])

In [16]:
random_array.reshape(2,3)

array([[0.36894683, 0.87635348, 0.38514518],
       [0.21442169, 0.56360497, 0.63600393]])

In [17]:
random_array.reshape(3,2)

array([[0.36894683, 0.87635348],
       [0.38514518, 0.21442169],
       [0.56360497, 0.63600393]])

In [18]:
data = np.array([10,12,13,14,18,25,100,105])

In [19]:
# Outlier

In [21]:
mean = np.mean(data)
mean

np.float64(37.125)

In [22]:
# 2x + 3y = 8, 5x + 7y = 19

In [24]:
A = np.array([[2,3], [5,7]])

In [25]:
b = np.array([8,19])

In [27]:
solution = np.linalg.solve(A,b)
solution

array([1., 2.])