In [2]:
import numpy as np

In [4]:
my_list = [10,20,30,40]

In [5]:
type(my_list)

list

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_list_array)

numpy.ndarray

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.random.random(5)

array([0.20055981, 0.04677546, 0.28292734, 0.81890643, 0.84270225])

In [12]:
# Array aritmatic

In [13]:
my_list1 = [1,2]

In [14]:
my_list2 = [2,3]

In [63]:
my_list1 ** 5 

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [23]:
my_list1 + my_list2

[1, 2, 2, 3]

In [24]:
my_list1 - my_list2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [25]:
my_list1 / my_list2

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [26]:
my_list1 * my_list2

TypeError: can't multiply sequence by non-int of type 'list'

In [27]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [17]:
my_numpy_array1 = np.array(my_list1)

In [18]:
my_numpy_array2 = np.array(my_list2)

In [19]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [20]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [21]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [22]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [28]:
my_numpy_array1 * 5

array([ 5, 10])

In [62]:
my_numpy_array1 ** 5

array([ 1, 32])

In [29]:
other_array = np.array([10,20,30,40,50])

In [31]:
# Boyutları farklı olduğundan toplayamayız
my_numpy_array1 + other_array

ValueError: operands could not be broadcast together with shapes (2,) (5,) 

In [32]:
##### INDEXING

In [34]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
np_array = np.arange(0,10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np_array[0]

np.int64(0)

In [40]:
np_array[-1]

np.int64(9)

In [41]:
np_array[1:4:]

array([1, 2, 3])

In [42]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [53]:
np.random.randn(4) # Normal dağılıma uygun veri üretir

array([1.07984638, 0.62727355, 1.50278414, 1.31820486])

In [56]:
np.random.randn(4,4)

array([[-0.43111854,  0.31678955, -0.19265125, -0.23629255],
       [-0.27278416, -0.97864887, -0.14952057, -0.31711909],
       [ 0.45199075, -0.50997716,  1.04216646,  0.15003614],
       [-0.11222034, -0.81496028,  0.91469875,  0.15416191]])

In [57]:
np.random.randn(4,4)

array([[-5.23981809e-01,  8.57680788e-01, -7.03384839e-01,
        -1.52105417e-03],
       [-1.25594992e+00, -9.19824595e-01,  6.37626230e-01,
        -1.03877770e+00],
       [ 2.62197220e+00, -7.69277263e-01,  1.29662654e-01,
        -3.71609733e-01],
       [-1.12960423e+00, -1.20120519e+00,  4.10660243e-01,
         6.90897467e-02]])

In [47]:
np.random.random(4) # 0 ile 1 arasında pozitif sayı üretir

array([0.47493641, 0.93434467, 0.51968042, 0.76258697])

In [59]:
np.random.random(4) 

array([0.7409352 , 0.09811416, 0.34470551, 0.00705304])

In [61]:
np.random.randint(1,300,5) #den başlayıp 300e kadar giden 5 tane random sayı verir.

array([130, 240, 281, 133, 254])